version: "2"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_USER: postgresuser
    volumes:
      - "./postgres/:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.3-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data/:/data/"

  mongo:
    image: mongo
    restart: always
    volumes:
      - "./mongo/data/:/data/db/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"

  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/:/var/lib/mysql/"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
