version: "2"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_USER: postgresuser
    volumes:
      - "./postgres/:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.3-alpine
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
